Update pan_getcert
Split code into obtaining vs installing a certificate.

diff --git a/pan_getcert b/pan_getcert
--- a/pan_getcert
+++ b/pan_getcert
@@ -1,90 +1,159 @@
 #!/bin/bash
 
-# Usage info
+## Usage info
 show_help() {
 cat << EOF
-Usage: ${0##*/} [-hv] [-f OUTFILE] [FILE]
-This script issues a certificate using ipa-getcert and upload it to a Palo Alto
-firewall or Panorama. Additionally it ensures the renewal process will update
-the certificate on the appliance.
+Usage: ${0##*/} [-hv] -n CERT_NAME [-Y] [OPTIONS] FQDN
+This script uploads a certificate issued by ipa-getcert to a Palo Alto firewall
+or Panorama.
 
-    -h          display this help and exit
-    -f OUTFILE  write the result to OUTFILE instead of standard output.
-    -v          verbose mode. Can be used multiple times for increased
-                verbosity.
+    FQDN                Fully qualified name of the Palo Alto firewall or Panorama
+                        interface. Must be reachable from this host on port TCP/443.
+
+OPTIONS:
+    -n CERT_NAME        REQUIRED. Name of the certificate in PanOS configuration.
+
+    -s PROFILE_NAME     Apply the certificate to a SSL/TLS Service Profile.
+                        (For example for a management interface).
+    -p [PROFILE_NAME]   Apply the certificate to a GlobalProtect SSL/TLS Service Profile
+                        used on the Portal. Omit this option to avoid automatic linking.
+                        Default profile name: GP_PORTAL_PROFILE
+    -g [PROFILE_NAME]   Apply the certificate to a GlobalProtect SSL/TLS Service Profile
+                        used on the Gateway. Omit this option to avoid automatic linking.
+                        Default proifile name: GP_EXT_GW_PROFILE
+    -Y                  Append the current year '_YYYY' to the certificate name. And
+                        when the certificate is automatically renewed.
+
+    -h                  Display this help and exit.
+    -v                  Verbose mode. Can be used multiple times for increased verbosity.
 EOF
 }
 
-## Variables
-PAN_MGMT=<FW_MGMT_FQDN>
-API_KEY=/etc/ipa/.panrc
-CERT_NAME=FreeIPA_DOMAIN.LOCAL
-GP_PORTAL_TLS_PROFILE=GP_PORTAL_PROFILE
-GP_GW_TLS_PROFILE=GP_EXT_GW_PROFILE
+## Fixed variables
+#GET_CERT="/usr/local/bin/pan_getcert"
+INST_CERT="/usr/local/bin/pan_instcert"
+API_KEY="/etc/ipa/.panrc"
 TEMP_PWD=$(openssl rand -hex 15)
-TEMP_PFX="/etc/ipa/ssl/getcert_pkcs12.pfx"
-GETCERT="/usr/local/bin/pan_getcert"
-output_file=""
-verbose=0
-
+TEMP_PFX="/tmp/getcert_pkcs12.pfx"
+VERBOSE=0
 OPTIND=1
-# Resetting OPTIND is necessary if getopts was used previously in the script.
-# It is a good idea to make OPTIND local if you process options in a function.
 
-while getopts hvf: opt; do
+## Read/interpret optional arguments
+while getopts n:s:pgvh opt; do
     case $opt in
-        h)
-            show_help
+        n)  CERT_NAME=$OPTARG
+            ;;
+        Y)  YEAR="_$(date +'%Y')"
+            ;;
+        s)  SSL_TLS_PROFILE=$OPTARG
+            ;;
+        p)  eval nextopt=${!OPTIND}
+            if [[ -n $nextopt && $nextopt != -* ]] ; then
+                OPTIND=$((OPTIND+1))
+                if [[ "$nextopt" =~ (^[\w-]+$) ]]; then
+                    GP_PORTAL_TLS_PROFILE=$nextopt
+                else
+                    printf 'ERROR: Invalid GP_PORTAL_TLS_PROFILE given: <%s>\n' "$nextopt"
+                    printf 'Ensure the name does not contain dots or spaces.\n'
+                    exit 2
+                fi
+            else
+                GP_PORTAL_TLS_PROFILE=GP_PORTAL_PROFILE
+            fi
+            ;;
+        p)  eval nextopt=${!OPTIND}
+            if [[ -n $nextopt && $nextopt != -* ]] ; then
+                OPTIND=$((OPTIND+1))
+                if [[ "$nextopt" =~ (^[\w-]+$) ]]; then
+                    GP_GW_TLS_PROFILE=$nextopt
+                else
+                    printf 'ERROR: Invalid GP_GW_TLS_PROFILE given: <%s>\n' "$nextopt"
+                    printf 'Ensure the name does not contain dots or spaces.\n'
+                    exit 3
+                fi
+            else
+                GP_GW_TLS_PROFILE=GP_EXT_GW_PROFILE
+            fi
+            ;;
+        v)  VERBOSE=$((VERBOSE+1))
+            ;;
+        h)  show_help
             exit 0
             ;;
-        v)  verbose=$((verbose+1))
-            ;;
-        f)  output_file=$OPTARG
-            ;;
-        *)
-            show_help >&2
+        *)  show_help >&2
             exit 1
             ;;
     esac
 done
 shift "$((OPTIND-1))"   # Discard the options and sentinel --
 
-# Everything that's left in "$@" is a non-option.  In our case, a FILE to process.
-printf 'verbose=<%d>\noutput_file=<%s>\nLeftovers:\n' "$verbose" "$output_file"
-printf '<%s>\n' "$@"
+# Check that a certificate name was given
+if [[ -z $CERT_NAME ]]; then
+    printf 'ERROR: missing -n, a certificate name is required.\n\n'
+    show-help >&2
+    exit 1
 
-## Requirements: openssl, pan-python, ipa-getcert
-
-## Create the folder for the certificate chains
-if [ -d /etc/ipa ]; then
-  sudo mkdir -p /etc/ipa/ssl
-  sudo chmod 700 /etc/ipa/ssl
+# Check that a single valid FQDN was parsed.
+if [[ "$@" =~ (?=^.{4,253}$)(^((?!-)[a-zA-Z0-9-]{1,63}(?<!-)\.)+[a-zA-Z]{2,63}$) ]]; then
+    PAN_MGMT="${@,,}"
+    printf 'verbose=<%d>\nCERT_NAME=<%s>\nFQDN=<%s>\n' "$VERBOSE" "$CERT_NAME$YEAR" "$PAN_MGMT"
+    (( $VERBOSE > 0 )) && printf 'GP_PORTAL_TLS_PROFILE=<%s>\nGP_GW_TLS_PROFILE=<%s>\n' "$GP_PORTAL_TLS_PROFILE" "$GP_GW_TLS_PROFILE"
+    if ! nc -z $PAN_MGMT 443 2>/dev/null; then
+        printf 'ERROR: Palo Alto device unreachable at: https://<%s>/\n' "$PAN_MGMT"
+        exit 4
+    fi
 else
-  echo '/etc/ipa/ does not exist. This host must tbe an active FreeIPA client'
-  exit 1
+    printf 'ERROR: A valid FQDN is required to issue a certificate.\n'
+    printf 'Parsed string: <%s>\n\n' "$@"
+    show_help >&2
+    exit 4
 fi
 
-#sudo ipa-getcert request -N ${PAN_MGMT} -K HTTP/${PAN_MGMT} \
-#  -k /etc/ssl/private/${PAN_MGMT}.key \
-#  -f /etc/ssl/certs/${PAN_MGMT}.crt \
-#  -D ${PAN_MGMT} -C { $GETCERT $PAN_MGMT }
+## Requirements
+# Installed packages: ipa-getcert
 
-# Create a password protected PKCS12 file
-sudo openssl pkcs12 -export -out '$TEMP_PFX' -inkey '/etc/ssl/private/${PAN_MGMT}.key' -in '/etc/ssl/certs/${PAN_MGMT}.crt' \
-  -certfile '/etc/ipa/ssl/${PAM_MGMT}_chain.pem' -passout pass:$TEMP_PWD
+# Ensure the host is enrolled into an IPA server and the folder for certificate chain storage exists.
+REALM=$(realm discover -n)
+if [ $? -eq 0 ]; then
+    echo 'ERROR: Realm not found. This script must be run from an enrolled FreeIPA client.'
+    exit 5
+fi
+if [ -d /etc/ipa ]; then
+    sudo mkdir -m 0700 -p /etc/ipa/ssl
+    if [ $? -eq 0 ]; then
+        printf 'ERROR: /etc/ipa/ssl could not be created.\n'
+        printf 'Ensure you have sudo rights to create this folder, or have it created for you\nowned by root and with privileges set to: 0700.\n'
+    exit 6
+else
+    echo 'ERROR: /etc/ipa/ does not exist. This script must be run from an enrolled FreeIPA client.'
+    exit 5
+fi
 
-# Upload it to the firewall
-curl -k --form file=@$TEMP_PFX "https://$PAN_MGMT/api/?type=import&category=certificate&certificate-name=$CERT_NAME&format=pkcs12&passphrase=$TEMP_PWD&key=$API_KEY" && echo " "
-curl -k --form file=@$TEMP_PFX "https://$PAN_MGMT/api/?type=import&category=private-key&certificate-name=$CERT_NAME&format=pkcs12&passphrase=$TEMP_PWD&key=$API_KEY" && echo " "
-sudo rm '$TEMP_PFX'
+## Request the certificate from FreeIPA
+if [[ ! -z $SSL_TLS_PROFILE ]]; then
+    INST_OPTS="-s $SSL_TLS_PROFILE"
+else
+    if [[ ! -z $GP_PORTAL_TLS_PROFILE ]]; then
+        INST_OPTS="-p $GP_PORTAL_TLS_PROFILE"
+    fi
+    if [[ ! -z $GP_GW_TLS_PROFILE ]]; then
+        INST_OPTS="$INST_OPTS -g $GP_GW_TLS_PROFILE"
+    fi
+fi
+# The Service Principals are assumed to exist, if they don't the status will not be MONITORING.
+if [[ -z $YEAR ]]; then
+    RENEW_CMD="$INST_CERT -n $CERT_NAME $INST_OPTS $PAN_MGMT"
+else
+    RENEW_CMD="$INST_CERT -n ${CERT_NAME}_"'$(date +"%Y")'" $INST_OPTS $PAN_MGMT"
+fi
+sudo ipa-getcert request -N $CERT_NAME -K HTTP/$CERT_NAME -k /etc/ssl/private/${CERT_NAME}.key -f /etc/ssl/certs/${CERT_NAME}.crt \
+    -D $CERT_NAME -C "$RENEW_CMD"
 
-# If you use a separate SSL/TLS Service Profile for the GlobalProtect Portal and Gateway, uncomment the next line and update the
-# 'GP_PORTAL_TLS_PROFILE' variable with the name of your GlobalProtect Portal's SSL/TLS Service Profile, as it appears in your management GUI.
-panxapi.py -h $PAN_MGMT -K $API_KEY -S "<certificate>$CERT_NAME</certificate>" "/config/shared/ssl-tls-service-profile/entry[@name='$GP_PORTAL_TLS_PROFILE']"
-
-# If you use a separate SSL/TLS Service Profile for the GlobalProtect Portal and Gateway, uncomment the next line and update the
-# 'GP_GW_TLS_PROFILE' variable with the name of your GlobalProtect Gateway's SSL/TLS Service Profile, as it appears in your management GUI. If you use a single SSL/TLS Service Profile for BOTH the Portal and Gateway, you can comment the following line out, or set the value of 'GP_GW_TLS_PROFILE' to the value of 'GP_PORTAL_TLS_PROFILE'
-panxapi.py -h $PAN_MGMT -K $API_KEY -S "<certificate>$CERT_NAME</certificate>" "/config/shared/ssl-tls-service-profile/entry[@name='$GP_GW_TLS_PROFILE']"
-
-# Save the changes
-panxapi.py -h $PAN_MGMT -K $API_KEY -C '' --sync
+# Verify state of the certificate is MONITORING
+if ! [[ $(sudo ipa-getcert status -f /etc/ssl/certs/${CERT_NAME}.crt) =~ "MONITORING" ]]; then
+    printf 'ERROR: Problem encountered with the requested certificate.\nManual intervention required.\n'
+    exit 10
+else
+    printf 'SUCCESS: Certificate issued for: <%s>.\nNow proceeding with installation to: <%s>.\n' "$CERT_NAME" "$PAN_MGMT"
+    $INST_CERT -n $CERT_NAME$YEAR $INST_OPTS $PAN_MGMT"
+fi
