Testing completed

diff --git a/pan_getcert b/pan_getcert
--- a/pan_getcert
+++ b/pan_getcert
@@ -7,75 +7,54 @@ Usage: ${0##*/} [-hv] -c CERT_CN [-n CERT_NAME] [-Y] [OPTIONS] FQDN
 This script requests a certificate from FreeIPA using ipa-getcert and calls a partner
 script to deploy the certificate to a Palo Alto firewall or Panorama.
 
-    FQDN                Fully qualified name of the Palo Alto firewall or Panorama
-                        interface. Must be reachable from this host on port TCP/443.
-    -c CERT_CN          REQUIRED. Common Name of the certificate (must be an FQDN). Will
-                        be added as to the certificate as a SAN.
+    FQDN              Fully qualified name of the Palo Alto firewall or Panorama
+                      interface. Must be reachable from this host on port TCP/443.
+    -c CERT_CN        REQUIRED. Common Name (Subject) of the certificate (must be a
+                      FQDN). Will also present in the certificate as a SAN.
 
 OPTIONS:
-    -n CERT_NAME        Name of the certificate in PanOS configuration. Defaults to the
-                        certificate Common Name.
-    -s PROFILE_NAME     Apply the certificate to a SSL/TLS Service Profile.
-                        (For example for a management interface).
-    -p [PROFILE_NAME]   Apply the certificate to a GlobalProtect SSL/TLS Service Profile
-                        used on the Portal. Omit this option to avoid automatic linking.
-                        Default profile name: GP_PORTAL_PROFILE
-    -g [PROFILE_NAME]   Apply the certificate to a GlobalProtect SSL/TLS Service Profile
-                        used on the Gateway. Omit this option to avoid automatic linking.
-                        Default proifile name: GP_EXT_GW_PROFILE
-    -Y                  Append the current year '_YYYY' to the certificate name. Also
-                        when the certificate is automatically renewed by ipa-getcert.
+    -n CERT_NAME      Name of the certificate in PanOS configuration. Defaults to the
+                      certificate Common Name.
+    -Y                Parsed to pan_instcert to append the current year '_YYYY' to
+                      the certificate name.
 
-    -h                  Display this help and exit.
-    -v                  Verbose mode.
+    -p PROFILE_NAME   Apply the certificate to a (primary) SSL/TLS Service Profile.
+    -s PROFILE_NAME   Apply the certificate to a (secondary) SSL/TLS Service Profile.
+
+    -h                Display this help and exit.
+    -v                Verbose mode.
 EOF
 }
 
 ## Fixed variables
 INST_CERT="/usr/local/bin/pan_instcert"
-API_KEY="/etc/ipa/.panrc"
 TEMP_PWD=$(openssl rand -hex 15)
-TEMP_PFX="/tmp/getcert_pkcs12.pfx"
 VERBOSE=0
 OPTIND=1
 
 ## Read/interpret optional arguments
-while getopts c:n:s:pgvh opt; do
+while getopts c:n:Yp:s:vh opt; do
     case $opt in
-        c)  CN_FQDN=$OPTARG
+        c)  CERT_CN=$OPTARG
             ;;
         n)  CERT_NAME=$OPTARG
             ;;
         Y)  YEAR="_$(date +'%Y')"
             ;;
-        s)  SSL_TLS_PROFILE=$OPTARG
-            ;;
-        p)  eval nextopt=${!OPTIND}
-            if [[ -n $nextopt && $nextopt != -* ]] ; then
-                OPTIND=$((OPTIND+1))
-                if [[ "$nextopt" =~ (^[\w-]+$) ]]; then
-                    GP_PORTAL_TLS_PROFILE=$nextopt
-                else
-                    printf 'ERROR: Invalid GP_PORTAL_TLS_PROFILE given: <%s>\n' "$nextopt"
-                    printf 'Ensure the name does not contain dots or spaces.\n'
-                    exit 2
-                fi
+        p)  if grep -q -P '(^[\w-]+$)' <<< "$OPTARG"; then
+                SSL_TLS_PROFILE_1=$OPTARG
             else
-                GP_PORTAL_TLS_PROFILE=GP_PORTAL_PROFILE
+                printf 'ERROR: Invalid first SSL/TLS Profile name given: %s\n' "$OPTARG"
+                printf 'Ensure the name does not contain dots or spaces.\n'
+                exit 2
             fi
             ;;
-        p)  eval nextopt=${!OPTIND}
-            if [[ -n $nextopt && $nextopt != -* ]] ; then
-                OPTIND=$((OPTIND+1))
-                if [[ "$nextopt" =~ (^[\w-]+$) ]]; then
-                    GP_GW_TLS_PROFILE=$nextopt
-                else
-                    printf 'ERROR: Invalid GP_GW_TLS_PROFILE given: <%s>\n' "$nextopt"
-                    printf 'Ensure the name does not contain dots or spaces.\n'
-                    exit 3
-                fi
+        s)  if grep -q -P '(^[\w-]+$)' <<< "$OPTARG"; then
+                SSL_TLS_PROFILE_2=$OPTARG
             else
-                GP_GW_TLS_PROFILE=GP_EXT_GW_PROFILE
+                printf 'ERROR: Invalid second SSL/TLS Profile name given: %s\n' "$OPTARG"
+                printf 'Ensure the name does not contain dots or spaces.\n'
+                exit 2
             fi
             ;;
         v)  VERBOSE=$((VERBOSE+1))
@@ -90,97 +69,103 @@ while getopts c:n:s:pgvh opt; do
 done
 shift "$((OPTIND-1))"   # Discard the options and sentinel --
 
+## This script must be run as root
+if [ "$EUID" -ne 0 ]
+    then echo "Please run as root"
+    exit
+fi
+
 # Check that a Common Name name was given
 if [[ -z $CERT_CN ]]; then
     printf 'ERROR: Missing -c, a certificate requires a Common Name.\n\n'
     show_help >&2
     exit 1
-elif [[ "$CERT_CN" =~ (?=^.{4,253}$)(^((?!-)[a-zA-Z0-9-]{1,63}(?<!-)\.)+[a-zA-Z]{2,63}$) ]]; then
-    $CERT_CN=${CERT_CN,,}
+elif grep -q -P '(?=^.{4,253}$)(^((?!-)[a-zA-Z0-9-]{1,63}(?<!-)\.)+[a-zA-Z]{2,63}$)' <<< "$CERT_CN"; then
+    CERT_CN=${CERT_CN,,}
     if (( $VERBOSE > 0 )); then
-        printf 'Certificate Common Name: <%s>' "$CERT_CN"
+        printf 'Certificate Common Name: %s\n' "$CERT_CN"
     fi
 fi
 if [[ -z $CERT_NAME ]]; then
-    $CERT_NAME=$CERT_CN
+    CERT_NAME=$CERT_CN
 elif (( $VERBOSE > 0 )); then
-    printf 'Parsed certificate Name: <%s>' "$CERT_NAME"
+    printf 'Parsed certificate Name: %s' "$CERT_NAME"
 fi
 
 # Check that a single valid FQDN was parsed for the Palo Alto API interface
-if [[ "$@" =~ (?=^.{4,253}$)(^((?!-)[a-zA-Z0-9-]{1,63}(?<!-)\.)+[a-zA-Z]{2,63}$) ]]; then
+if grep -q -P '(?=^.{4,253}$)(^((?!-)[a-zA-Z0-9-]{1,63}\.)+[a-zA-Z]{2,63}$)' <<< "$@"; then
     PAN_MGMT="${@,,}"
-    printf 'verbose=<%d>\nCERT_CN=<%s>\nCERT_NAME=<%s>\nFQDN=<%s>\n' "$VERBOSE" "$CERT_CN" "$CERT_NAME$YEAR" "$PAN_MGMT"
+    printf '  verbose=%d\n  CERT_CN: %s\n  CERT_NAME: %s\n  PAN_FQDN: %s\n' "$VERBOSE" "$CERT_CN" "$CERT_NAME$YEAR" "$PAN_MGMT"
     if ! nc -z $PAN_MGMT 443 2>/dev/null; then
-        printf 'ERROR: Palo Alto device unreachable at: https://<%s>/\n' "$PAN_MGMT"
+        printf 'ERROR: Palo Alto device unreachable at: https://%s/\n' "$PAN_MGMT"
         exit 4
     fi
 else
     printf 'ERROR: A valid FQDN is required to issue a certificate.\n'
-    printf 'Parsed string: <%s>\n\n' "$@"
+    printf 'Parsed string: %s\n\n' "$@"
     show_help >&2
     exit 4
 fi
 
-# Verbose stdout of SSL/TLS profiles (if any)
-if (( $VERBOSE > 0 )) && [[ ! -z $SSL_TLS_PROFILE ]]; then
-    printf 'SSL/TLS profile SSL_TLS_PROFILE=<%s>\n' "$SSL_TLS_PROFILE"
-elif (( $VERBOSE > 0 )) && [[ ! -z $GP_PORTAL_TLS_PROFILE || ! -z $GP_GW_TLS_PROFILE ]]; then
-    printf 'SSL/TLS profile GP_PORTAL_TLS_PROFILE=<%s>\nSSL/TLS profile GP_GW_TLS_PROFILE=<%s>\n' "$GP_PORTAL_TLS_PROFILE" "$GP_GW_TLS_PROFILE"
-elif (( $VERBOSE > 0 )); then
-    echo "No SSL/TLS profiles parsed."
+# Parse YEAR option to pan_instcert
+if [[ -z $YEAR ]]; then
+    INST_OPTS=""
+else
+    INST_OPTS="-Y"
+fi
+
+# Verbosely log SSL/TLS profile names (if any) and only allow secondary if a primary is given
+if [[ ! -z $SSL_TLS_PROFILE_1 ]]; then
+    INST_OPTS="$INST_OPTS -p $SSL_TLS_PROFILE_1"
+    (( $VERBOSE > 0 )) && printf 'Primary SSL/TLS Profile name: %s\n' "$SSL_TLS_PROFILE_1"
+    if [[ ! -z $SSL_TLS_PROFILE_2 ]]; then
+        INST_OPTS="$INST_OPTS -s $SSL_TLS_PROFILE_2"
+        (( $VERBOSE > 0 )) && printf 'Secondary SSL/TLS Profile name: %s\n' "$SSL_TLS_PROFILE_2"
+    fi
+else
+    SSL_TLS_PROFILE_2=""
+    (( $VERBOSE > 0 )) && echo "No SSL/TLS Profile names parsed."
 fi
 
 ## Requirements
 # Installed packages: ipa-getcert
 
-# Ensure the host is enrolled into an IPA server and the folder for certificate chain storage exists.
-REALM=$(realm discover -n)
-if [ $? -eq 0 ]; then
-    echo 'ERROR: Realm not found. This script must be run from an enrolled FreeIPA client.'
-    exit 5
-fi
-if [ -d /etc/ipa ]; then
-    sudo mkdir -m 0700 -p /etc/ipa/ssl
-    if [ $? -eq 0 ]; then
-        printf 'ERROR: /etc/ipa/ssl could not be created.\n'
-        printf 'Ensure you have sudo rights to create this folder, or have it created for you\nowned by root and with privileges set to: 0700.\n'
-    exit 6
-else
+# Simple check to see if freeipa-client is installed.
+if [[ ! -d /etc/ipa ]]; then
     echo 'ERROR: /etc/ipa/ does not exist. This script must be run from an enrolled FreeIPA client.'
     exit 5
 fi
 
 ## Request the certificate from FreeIPA
-if [[ ! -z $SSL_TLS_PROFILE ]]; then
-    INST_OPTS="-s $SSL_TLS_PROFILE"
-else
-    if [[ ! -z $GP_PORTAL_TLS_PROFILE ]]; then
-        INST_OPTS="-p $GP_PORTAL_TLS_PROFILE"
-    fi
-    if [[ ! -z $GP_GW_TLS_PROFILE ]]; then
-        INST_OPTS="$INST_OPTS -g $GP_GW_TLS_PROFILE"
-    fi
-fi
-# The Service Principals are assumed to exist, if they don't the status will not be MONITORING.
-if [[ -z $YEAR ]]; then
-    sudo ipa-getcert request -N $CERT_CN -K HTTP/$CERT_CN -k /etc/ssl/private/${CERT_CN}.key -f /etc/ssl/certs/${CERT_CN}.crt \
-    -D $CERT_CN -C "$INST_CERT -n $CERT_NAME $INST_OPTS $PAN_MGMT"
-else
-    sudo ipa-getcert request -N $CERT_CN -K HTTP/$CERT_CN -k /etc/ssl/private/${CERT_CN}.key -f /etc/ssl/certs/${CERT_CN}.crt \
-    -D $CERT_CN -C "$INST_CERT -n ${CERT_NAME}_"'$(date +"%Y")'" $INST_OPTS $PAN_MGMT"
-fi
+ipa-getcert request -N $CERT_CN -K HTTP/$CERT_CN -k /etc/ssl/private/${CERT_CN}.key -f /etc/ssl/certs/${CERT_CN}.crt -D $CERT_CN -C "$INST_CERT -c $CERT_CN -n $CERT_NAME $INST_OPTS $PAN_MGMT"
 if (( $VERBOSE > 0 )); then
-    printf 'Certificate requested for: <%s>' "$CERT_CN"
+    printf 'Certificate requested for: %s\n' "$CERT_CN"
 fi
 
-# Verify state of the certificate is MONITORING
-CERT_STATUS=$(sudo ipa-getcert status -f /etc/ssl/certs/${CERT_CN}.crt -v)
-if ! [[ $CERT_STATUS =~ "MONITORING" ]]; then
-    printf 'ERROR: Problem encountered with the requested certificate.\nManual intervention required for: <%s>.\n' "$CERT_CN"
-    printf 'Certificate request <%s>\n' "${CERT_STATUS,}"
+# Verify state of the certificate is MONITORING, use a 300 second timeout.
+STEP=1
+SECONDS=0
+CERT_STAT="requested"
+while [[ $SECONDS -lt 300 ]] && [[ "$CERT_STAT" != "monitoring" ]]; do
+    sleep $STEP
+    (( $VERBOSE > 0 )) && printf '\r  Waiting for status: %d seconds.' "$SECONDS"
+    if [[ $(ipa-getcert status -f /etc/ssl/certs/${CERT_CN}.crt -v) =~ (POST_SAVED_CERT) ]] && [[ "$CERT_STAT" == "requested" ]]; then
+        C_ISSUE=$SECONDS
+        printf '\r  Certificate issue took %d seconds, waiting for the post-save process to finish.\n' "$C_ISSUE"
+        CERT_STAT="post_saved_cert"
+    elif [[ $(ipa-getcert status -f /etc/ssl/certs/${CERT_CN}.crt -v) =~ (MONITORING) ]]; then
+        printf '\r  Certificate install and commit by the post-save process on: %s took %d seconds.\n' "$PAN_MGMT" "(($SECONDS-$C_ISSUE))"
+        CERT_STAT="monitoring"
+    fi
+done
+if [[ "$CERT_STAT" != "monitoring" ]]; then
+    printf 'ERROR: Problem encountered with the requested certificate or installation.\nManual intervention required for: %s\n' "$CERT_CN"
+    CMD="ipa-getcert status -f /etc/ssl/certs/${CERT_CN}.crt -v"
+    CERT_STATUS=$($CMD)
+    printf ' - Certificate request - %s\nCheck Certmonger status with: %s\n' "${CERT_STATUS,}" "$CMD"
+    printf ' - Once resolved run the following command to deploy the certificate:\n   %s\n' "ipa-getcert resubmit -f /etc/ssl/certs/${CERT_CN}.crt"
+    printf ' - If stuck in POST_SAVED_CERT, then the post-save command likely failed.\n   Check /var/log/pan_instcert.log, CPU load and abort the post-save process.\n\n'
     exit 10
-else
-    printf 'SUCCESS: Certificate issued for: <%s>.\nProceeding with installation to: <%s>.\n' "$CERT_CN" "$PAN_MGMT"
-    #$INST_CERT -n $CERT_NAME$YEAR $INST_OPTS $PAN_MGMT" # post-save may work on initial issue of the certificate -- TO BE VERIFIED
 fi
+echo "FINISHED: Check the Palo Alto firewall or Panorama to check the commit succeeded."
+
diff --git a/pan_instcert b/pan_instcert
--- a/pan_instcert
+++ b/pan_instcert
@@ -1,71 +1,68 @@
 #!/bin/bash
 
+## Logging
+LOG="/var/log/pan_instcert.log"
+wlog() {
+    printf "$*"
+    printf "[$(date --rfc-3339=seconds)]: $*" >> "$LOG"
+}
+trap 'wlog "ERROR - Certificate installation failed.\n"' TERM HUP
+
 ## Usage info
 show_help() {
 cat << EOF
-Usage: ${0##*/} [-hv] -n CERT_NAME [OPTIONS] FQDN
+Usage: ${0##*/} [-hv] -c CERT_CN [-n CERT_NAME] [OPTIONS] FQDN
 This script uploads a certificate issued by ipa-getcert to a Palo Alto firewall
-or Panorama.
+or Panorama and optionally adds it to up to two SSL/TLS Profiles.
 
-    FQDN                Fully qualified name of the Palo Alto firewall or Panorama
-                        interface. Must be reachable from this host on port TCP/443.
-    -n CERT_NAME        REQUIRED. Name of the certificate in PanOS configuration.
+    FQDN              Fully qualified name of the Palo Alto firewall or Panorama
+                      interface. Must be reachable from this host on port TCP/443.
+    -c CERT_CN        REQUIRED. Common Name (Subject) of the certificate, to find
+                      the certificate and key files.
 
 OPTIONS:
-    -s PROFILE_NAME     Apply the certificate to a SSL/TLS Service Profile.
-                        (For example for a management interface).
-    -p [PROFILE_NAME]   Apply the certificate to a GlobalProtect SSL/TLS Service Profile
-                        used on the Portal. Omit this option to avoid automatic linking.
-                        Default profile name: GP_PORTAL_PROFILE
-    -g [PROFILE_NAME]   Apply the certificate to a GlobalProtect SSL/TLS Service Profile
-                        used on the Gateway. Omit this option to avoid automatic linking.
-                        Default proifile name: GP_EXT_GW_PROFILE
+    -n CERT_NAME      Name of the certificate in PanOS configuration. Defaults to the
+                      certificate Common Name.
+    -Y                Append the current year '_YYYY' to the certificate name.
 
-    -h                  Display this help and exit.
-    -v                  Verbose mode.
+    -p PROFILE_NAME   Apply the certificate to a (primary) SSL/TLS Service Profile.
+    -s PROFILE_NAME   Apply the certificate to a (secondary) SSL/TLS Service Profile.
+
+    -h                Display this help and exit.
+    -v                Verbose mode.
 EOF
 }
 
 ## Fixed variables
 API_KEY="/etc/ipa/.panrc"
-TEMP_PWD=$(openssl rand -hex 15)
 TEMP_PFX="/tmp/getcert_pkcs12.pfx"
+TEMP_PWD=$(openssl rand -hex 15)
 VERBOSE=0
 OPTIND=1
 
 ## Read/interpret optional arguments
-while getopts n:s:pgvh opt; do
+while getopts c:n:Yp:s:vh opt; do
     case $opt in
+        c)  CERT_CN=$OPTARG
+            ;;
         n)  CERT_NAME=$OPTARG
             ;;
-        s)  SSL_TLS_PROFILE=$OPTARG
+        Y)  YEAR="_$(date +'%Y')"
             ;;
-        p)  eval nextopt=${!OPTIND}
-            if [[ -n $nextopt && $nextopt != -* ]] ; then
-                OPTIND=$((OPTIND+1))
-                if [[ "$nextopt" =~ (^[\w-]+$) ]]; then
-                    GP_PORTAL_TLS_PROFILE=$nextopt
-                else
-                    printf 'ERROR: Invalid GP_PORTAL_TLS_PROFILE given: <%s>\n' "$nextopt"
-                    printf 'Ensure the name does not contain dots or spaces.\n'
-                    exit 2
-                fi
+        p)  if grep -q -P '(^[\w-]+$)' <<< "$OPTARG"; then
+                SSL_TLS_PROFILE_1=$OPTARG
             else
-                GP_PORTAL_TLS_PROFILE=GP_PORTAL_PROFILE
+                printf 'ERROR: Invalid first SSL/TLS Profile name given: %s\n' "$OPTARG"
+                printf 'Ensure the name does not contain dots or spaces.\n'
+                exit 2
             fi
             ;;
-        p)  eval nextopt=${!OPTIND}
-            if [[ -n $nextopt && $nextopt != -* ]] ; then
-                OPTIND=$((OPTIND+1))
-                if [[ "$nextopt" =~ (^[\w-]+$) ]]; then
-                    GP_GW_TLS_PROFILE=$nextopt
-                else
-                    printf 'ERROR: Invalid GP_GW_TLS_PROFILE given: <%s>\n' "$nextopt"
-                    printf 'Ensure the name does not contain dots or spaces.\n'
-                    exit 3
-                fi
+        s)  if grep -q -P '(^[\w-]+$)' <<< "$OPTARG"; then
+                SSL_TLS_PROFILE_2=$OPTARG
             else
-                GP_GW_TLS_PROFILE=GP_EXT_GW_PROFILE
+                printf 'ERROR: Invalid second SSL/TLS Profile name given: %s\n' "$OPTARG"
+                printf 'Ensure the name does not contain dots or spaces.\n'
+                exit 2
             fi
             ;;
         v)  VERBOSE=$((VERBOSE+1))
@@ -80,93 +77,143 @@ while getopts n:s:pgvh opt; do
 done
 shift "$((OPTIND-1))"   # Discard the options and sentinel --
 
-# Check that a certificate name was given
-if [[ -z $CERT_NAME ]]; then
-    printf 'ERROR: missing -n, a certificate name is required.\n\n'
-    show-help >&2
-    exit 1
+## This script must be run as root
+if [ "$EUID" -ne 0 ]; then
+    echo "Please run as root"
+    exit
 fi
 
-# Check that a single valid FQDN was parsed.
-if [[ "$@" =~ (?=^.{4,253}$)(^((?!-)[a-zA-Z0-9-]{1,63}(?<!-)\.)+[a-zA-Z]{2,63}$) ]]; then
+## Start logging
+wlog "START of pan_instcert.\n"
+
+# Check that a Common Name name was given
+if [[ -z $CERT_CN ]]; then
+    wlog "ERROR: Missing -c, a certificate requires a Common Name.\n\n"
+    show_help >&2
+    exit 1
+elif grep -q -P '(?=^.{4,253}$)(^((?!-)[a-zA-Z0-9-]{1,63}(?<!-)\.)+[a-zA-Z]{2,63}$)' <<< "$CERT_CN"; then
+    CERT_CN=${CERT_CN,,}
+    wlog "Certificate Common Name: $CERT_CN\n"
+fi
+if [[ -z $CERT_NAME ]]; then
+    CERT_NAME=$CERT_CN
+fi
+# Append the current year to CERT_NAME if requested [-Y]
+CERT_NAME="$CERT_NAME$YEAR"
+
+(( $VERBOSE > 0 )) && wlog "Parsed certificate Name: $CERT_NAME\n"
+
+# Check that a single valid FQDN was parsed for the Palo Alto API interface
+if grep -q -P '(?=^.{4,253}$)(^((?!-)[a-zA-Z0-9-]{1,63}\.)+[a-zA-Z]{2,63}$)' <<< "$@"; then
     PAN_MGMT="${@,,}"
-    printf 'verbose=<%d>\nCERT_NAME=<%s>\nFQDN=<%s>\n' "$VERBOSE" "$CERT_NAME" "$PAN_MGMT"
-    (( $VERBOSE > 0 )) && printf 'GP_PORTAL_TLS_PROFILE=<%s>\nGP_GW_TLS_PROFILE=<%s>\n' "$GP_PORTAL_TLS_PROFILE" "$GP_GW_TLS_PROFILE"
+    (( $VERBOSE > 0 )) && wlog "PAN_FQDN: $PAN_MGMT\n"
     if ! nc -z $PAN_MGMT 443 2>/dev/null; then
-        printf 'ERROR: Palo Alto device unreachable on TCP/443 at: <%s>' "$PAN_MGMT"
+        wlog "ERROR: Palo Alto device unreachable at: https://$PAN_MGMT/\n"
         exit 4
     fi
 else
-    printf 'ERROR: A valid FQDN is required to issue a certificate.\n'
-    printf 'Parsed string: <%s>\n\n' "$@"
+    wlog "ERROR: A valid FQDN is required to issue a certificate.\n"
+    wlog "Parsed string: $@\n\n"
     show_help >&2
     exit 4
+fi
+
+# Verbosely log SSL/TLS profile names, only allow secondary if a primary is given
+if [[ ! -z $SSL_TLS_PROFILE_1 ]]; then
+    (( $VERBOSE > 0 )) && wlog "Primary SSL/TLS Profile name: $SSL_TLS_PROFILE_1\n"
+    if [[ ! -z $SSL_TLS_PROFILE_2 ]]; then
+        (( $VERBOSE > 0 )) && wlog "Secondary SSL/TLS Profile name: $SSL_TLS_PROFILE_2\n"
+    fi
+else
+    SSL_TLS_PROFILE_2=""
+    (( $VERBOSE > 0 )) && wlog "No SSL/TLS Profile names parsed.\n"
 fi
 
 ## Requirements
 # Installed packages: openssl, pan-python
 
-# Ensure the host is enrolled into an IPA server and the folder for certificate chain storage exists.
-REALM=$(realm discover -n)
-if [ $? -eq 0 ]; then
-    echo 'ERROR: Realm not found. This script must be run from an enrolled FreeIPA client.'
+# Verify the API key exists
+if ! grep -q -P '^api_key=' "$API_KEY"; then
+    wlog "ERROR: File missing or no API key found in: $API_KEY\n"
     exit 5
-fi
-if [ -d /etc/ipa ]; then
-    sudo mkdir -m 0700 -p /etc/ipa/ssl
-    if [ $? -eq 0 ]; then
-        printf 'ERROR: /etc/ipa/ssl could not be created.\n'
-        printf 'Ensure you have sudo rights to create this folder, or have it created for you\nowned by root and with privileges set to: 0700.\n'
-    exit 6
 else
-    echo 'ERROR: /etc/ipa/ does not exist. This script must be run from an enrolled FreeIPA client.'
-    exit 5
+    (( $VERBOSE > 0 )) && wlog "API key found in: $API_KEY\n"
+    # Commit the cardinal sin of changing the type of the variable from file-path to string.
+    API_KEY=$(grep -P '^api_key=' "$API_KEY")
+    API_KEY="${API_KEY#api_key=}"
 fi
 
 ## Upload and install the certificate to Palo Alto firewall or Panorama.
-# Verify state of the certificate is MONITORING
-if ! [[ $(sudo ipa-getcert status -f /etc/ssl/certs/${CERT_NAME}.crt) =~ "MONITORING" ]]; then
-    printf 'ERROR: Problem encountered with the requested certificate.\nInstallation aborted.\n'
-    exit 10
+# Verify state of the certificate is MONITORING or POST_SAVED_CERT
+KEY_FILE="/etc/ssl/private/${CERT_CN}.key"
+CRT_FILE="/etc/ssl/certs/${CERT_CN}.crt"
+CERT_STATUS=$(ipa-getcert status -f "$CRT_FILE" -v)
 # Verify both certificate and key files exist
-elif [[ ! -f '/etc/ssl/private/${PAN_MGMT}.key' ]] || [[ ! -f '/etc/ssl/certs/${PAN_MGMT}.crt' ]]; then
-    printf 'ERROR: Missing certificate or key files. Check if the following files exist:\n'
-    printf 'Key file:<%s>\nCert file:<%s>\n' "/etc/ssl/private/${PAN_MGMT}.key" "/etc/ssl/certs/${PAN_MGMT}.crt"
+if [[ ! -f "$KEY_FILE" ]] || [[ ! -f "$CRT_FILE" ]]; then
+    wlog "ERROR: Missing certificate or key files. Check if the following files exist:\n"
+    wlog "Key file: $KEY_FILE\nCert file: $CRT_FILE\n"
+    exit 10
+elif ! [[ "$CERT_STATUS" =~ (MONITORING|POST_SAVED_CERT) ]]; then
+    wlog 'ERROR: Problem encountered with the requested certificate.\nInstallation aborted, verify that the certificate status is "MONITORING".\n'
     exit 11
+else
+    (( $VERBOSE > 0 )) && wlog "Certmonger certificate ${CERT_STATUS,}\n"
 fi
+printf '\n'
 
-# Create a password protected PKCS12 file
-sudo openssl pkcs12 -export -out '$TEMP_PFX' -inkey '/etc/ssl/private/${PAN_MGMT}.key' -in '/etc/ssl/certs/${PAN_MGMT}.crt' \
-    -certfile '/etc/ipa/ssl/${PAM_MGMT}_chain.pem' -passout pass:$TEMP_PWD
+# Create a password protected PKCS12 file. If you need an intermediary certificate Manually load it on the Palo Alto firewall or Panorama.
+openssl pkcs12 -export -out "$TEMP_PFX" -inkey "$KEY_FILE" -in "$CRT_FILE" -passout pass:$TEMP_PWD
 
 # Upload it to the firewall
-curl -k --form file=@$TEMP_PFX "https://$PAN_MGMT/api/?type=import&category=certificate&certificate-name=$CERT_NAME&format=pkcs12&passphrase=$TEMP_PWD&key=$API_KEY" && echo " "
-curl -k --form file=@$TEMP_PFX "https://$PAN_MGMT/api/?type=import&category=private-key&certificate-name=$CERT_NAME&format=pkcs12&passphrase=$TEMP_PWD&key=$API_KEY" && echo " "
-sudo rm '$TEMP_PFX'
-if (( $VERBOSE > 0 )); then
-    printf '<%s> has been set deployed to: <%s>' "$CERT_NAME" "$PAN_MGMT"
+OUTPUT=$(curl -k --form file=@$TEMP_PFX "https://$PAN_MGMT/api/?type=import&category=certificate&certificate-name=$CERT_NAME&format=pkcs12&passphrase=$TEMP_PWD&key=$API_KEY" && echo " ")
+CRT_STATUS=$?
+wlog "XML API output for crt: $OUTPUT\n"
+if [ $CRT_STATUS -eq 0 ]; then
+    OUTPUT=$(curl -k --form file=@$TEMP_PFX "https://$PAN_MGMT/api/?type=import&category=private-key&certificate-name=$CERT_NAME&format=pkcs12&passphrase=$TEMP_PWD&key=$API_KEY" && echo " ")
+    KEY_STATUS=$?
+    wlog "XML API output for key: $OUTPUT\n"
+    if [ $KEY_STATUS -eq 0 ]; then
+        wlog "Finished uploading certificate: $CERT_NAME\n"
+    elif [ $KEY_STATUS -ne 0 ]; then
+        wlog "ERROR: Upload of key failed.\n"
+        exit 12
+    fi
+else
+    wlog "ERROR: Upload of certificate failed.\n"
+    exit 12
 fi
+rm "$TEMP_PFX"
 
 # Install/update the certificate to given SSL/TLS Profile(s)
-if [[ ! -z $SSL_TLS_PROFILE ]]; then
-    panxapi.py -h $PAN_MGMT -K $API_KEY -S "<certificate>$CERT_NAME</certificate>" "/config/shared/ssl-tls-service-profile/entry[@name='$SSL_TLS_PROFILE']"
-    PROFILES=$SSL_TLS_PROFILE
-else
-    if [[ ! -z $GP_PORTAL_TLS_PROFILE ]]; then
-        panxapi.py -h $PAN_MGMT -K $API_KEY -S "<certificate>$CERT_NAME</certificate>" "/config/shared/ssl-tls-service-profile/entry[@name='$GP_PORTAL_TLS_PROFILE']"
-        PROFILES=$GP_PORTAL_TLS_PROFILE
+if [[ ! -z $SSL_TLS_PROFILE_1 ]]; then
+    RESULT=$(/usr/local/bin/panxapi.py -h $PAN_MGMT -K $API_KEY -S "<certificate>$CERT_NAME</certificate>" "/config/shared/ssl-tls-service-profile/entry[@name='$SSL_TLS_PROFILE_1']" 2>&1)
+    (( $VERBOSE > 0 )) && wlog "$RESULT\n"
+    if [[ "$RESULT" =~ (command succeeded) ]]; then
+        PROFILES=$SSL_TLS_PROFILE_1
+	wlog "Successfully updated SSL/TLS Profile $SSL_TLS_PROFILE_1\n"
+    else
+        wlog "ERROR: Update of SSL/TLS Profile $SSL_TLS_PROFILE_1 failed.\n"
     fi
-    if [[ ! -z $GP_GW_TLS_PROFILE ]]; then
-        panxapi.py -h $PAN_MGMT -K $API_KEY -S "<certificate>$CERT_NAME</certificate>" "/config/shared/ssl-tls-service-profile/entry[@name='$GP_GW_TLS_PROFILE']"
-        PROFILES="$PROFILES $GP_GW_TLS_PROFILE"
+    if [[ ! -z $SSL_TLS_PROFILE_2 ]]; then
+        RESULT=$(/usr/local/bin/panxapi.py -h $PAN_MGMT -K $API_KEY -S "<certificate>$CERT_NAME</certificate>" "/config/shared/ssl-tls-service-profile/entry[@name='$SSL_TLS_PROFILE_2']" 2>&1)
+        (( $VERBOSE > 0 )) && wlog "$RESULT\n"
+	if [[ "$RESULT" =~ (command succeeded) ]]; then
+       	    PROFILES="$PROFILES $SSL_TLS_PROFILE_2"
+	    wlog "Successfully updated SSL/TLS Profile $SSL_TLS_PROFILE_2\n"
+        else
+            wlog "ERROR: Update of SSL/TLS Profile $SSL_TLS_PROFILE_2 failed.\n"
+	fi
     fi
 fi
 if (( $VERBOSE > 0 )) && [[ ! -z $PROFILES ]]; then
-    printf '<%s> has been set on SSL/TLS profile: <%s>' "$CERT_NAME" "$PROFILES"
+    wlog "$CERT_NAME has been set on SSL/TLS Profile(s): $PROFILES\n"
 fi
 
 ## Save/commit the changes
-panxapi.py -h $PAN_MGMT -K $API_KEY -C '' --sync
-if (( $VERBOSE > 0 )); then
-    printf 'The configuration on <%s> has been saved/synced.' "$PAN_MGMT"
-fi
+wlog "Starting commit, please be patient.\n"
+SECONDS=0
+RESULT=$(/usr/local/bin/panxapi.py -h $PAN_MGMT -K $API_KEY -C '' --sync 2>&1)
+wlog "$RESULT\n"
+wlog "The commit took $SECONDS seconds to complete.\n"
+wlog "END - Finished certificate installation to: $PAN_MGMT\n"
+
