Added IPA CA Certificate Profile and key type/length options

diff --git a/pan_getcert b/pan_getcert
--- a/pan_getcert
+++ b/pan_getcert
@@ -17,6 +17,13 @@ OPTIONS:
                       certificate Common Name.
     -Y                Parsed to pan_instcert to append the current year '_YYYY' to
                       the certificate name.
+    -T CERT_PROFILE   Ask IPA to process the request using the named profile or
+                      template.
+    -G TYPE           Type of key to be generated if one is not already in place.
+                      IPA CS uses RSA by default. (RSA, DSA, EC or ECDSA)
+    -B BITS           In case a new key pair needs to be generated, this option
+                      specifies the size of the key. Default: 2048 (RSA).
+                      ECDSA: 256, 384 or 512. See certmonger.conf for the default.
 
     -p PROFILE_NAME   Apply the certificate to a (primary) SSL/TLS Service Profile.
     -s PROFILE_NAME   Apply the certificate to a (secondary) SSL/TLS Service Profile.
@@ -33,13 +40,19 @@ VERBOSE=0
 OPTIND=1
 
 ## Read/interpret optional arguments
-while getopts c:n:Yp:s:vh opt; do
+while getopts c:n:YT:G:B:p:s:vh opt; do
     case $opt in
         c)  CERT_CN=$OPTARG
             ;;
         n)  CERT_NAME=$OPTARG
             ;;
         Y)  YEAR="_$(date +'%Y')"
+            ;;
+        T)  CERT_PROFILE=$OPTARG
+            ;;
+        G)  TYPE=$OPTARG
+            ;; 
+        B)  BITS=$OPTARG
             ;;
         p)  if grep -q -P '(^[\w-]+$)' <<< "$OPTARG"; then
                 SSL_TLS_PROFILE_1=$OPTARG
@@ -107,11 +120,52 @@ else
     exit 4
 fi
 
+# Verify a valid IPA CA Certificate Profile is parsed
+if [[ ! -z $CERT_PROFILE ]] && ipa certprofile-find --id=$CERT_PROFILE; then
+    printf "ERROR: Certificate profile %s doesn't exist" "$CERT_PROFILE"
+    exit 6
+fi
+
+# Verify the parsed certificate type and bit length
+if [[ ! -z $TYPE ]]; then
+    $TYPE=${TYPE^^}
+    if [[ "$TYPE" =~ ^(RSA|DSA)$ ]]; then
+        if [ "$BITS" -lt 2048 ]; then
+            printf 'ERROR: RSA/DSA key length must be at least 2048 bits'
+            exit 6
+        else
+            (( $VERBOSE > 0 )) && printf 'Key type/length: %s/%d' "$TYPE" "$BITS"
+        fi
+    elif [[ "$TYPE" =~ ^(EC|ECDSA)$ ]]; then
+        if [ "$BITS" -lt 256 ]; then
+            printf 'ERROR: EC/ECDSA key longth must be at least 256 bits'
+            exit 6
+        else
+            (( $VERBOSE > 0 )) && printf 'Key type/length: %s/%d' "$TYPE" "$BITS"
+        fi
+    else
+        printf 'ERROR: Unsupported key type: %s' "$TYPE"
+        exit 6
+    fi
+fi
+
 # Parse YEAR option to pan_instcert
 if [[ -z $YEAR ]]; then
     INST_OPTS=""
 else
     INST_OPTS="-Y"
+fi
+
+# Parse IPA CA Certificate Profile to pan_instcert
+if [[ ! -z $CERT_PROFILE ]]; then
+    INST_OPTS="$INST_OPTS -T $CERT_PROFILE"
+fi
+# Parse certificate key type and length to pan_instcert
+if [[ ! -z $TYPE ]]; then
+    INST_OPTS="$INST_OPTS -G $TYPE"
+    if [[ ! -z $BITS ]]; then
+         INST_OPTS="$INST_OPTS -G $BITS"
+    fi
 fi
 
 # Verbosely log SSL/TLS profile names (if any) and only allow secondary if a primary is given
